title: CyberSentinel - AI IDS IPS
description: >
  AI-Powered Intrusion Detection and Prevention System
  with 99.92% accuracy. Real-time network security
  using Machine Learning, Flask, and Scapy.
  Built by Malik Taha - BS Cybersecurity Pakistan.
url: https://github.com/MalikTaha8331/ai-ids-fyp
author: Malik Taha
keywords:
  - cybersecurity
  - intrusion detection
  - machine learning
  - python
  - flask
  - network security
  - pakistan